"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getCookie } from "cookies-next"; // client-side cookie API
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Metadata for the page
export const metadata = {
  title: "Dashboard - Govora Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

export default function AdminGuardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isLoading, setIsLoading] = useState(true);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const router = useRouter();

  useEffect(() => {
    // Check for cookies on mount
    const token = getCookie("jwttoken");
    const username = getCookie("username");
    const firstname = getCookie("firstname");

    if (!token || !username || !firstname) {
      // Redirect to login if any cookie is missing
      router.push("/login");
      return;
    }

    // User is authenticated if all cookies are found
    setIsAuthenticated(true);
    setIsLoading(false);
  }, [router]);

  // Show loading state while checking authentication
  if (isLoading) {
    return <div>Loading...</div>;
  }

  // Render children only if authenticated
  if (!isAuthenticated) {
    return null; // Or handle differently if needed
  }

  return (
    <>
      <div>{children}</div>
      <ToastContainer />
    </>
  );
}
