import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";

const RoobertPRO = localFont({
  src: [
    {
      path: "./fonts/RoobertPRO-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/RoobertPRO-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/RoobertPRO-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/RoobertPRO-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap", // Optional: CSS display property for font loading
});

export const metadata: Metadata = {
  title: "Welcome to Govora Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RoobertPRO.className} antialiased bg-green-50`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
