import type { Metadata } from "next";
import Aside from "./aside";

export const metadata: Metadata = {
  title: "Login - Govora Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Path to your favicon
  },
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-[350px_auto]">
      <Aside />
      <div className="p-10">{children}</div>
    </div>
  );
}
