import type { Metadata } from "next";
import Aside from "./aside";
import AdminGuardLayout from "@/components/layout/AdminGuard";

export const metadata: Metadata = {
  title: "Login - Govora Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Path to your favicon
  },
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AdminGuardLayout>
      <div className="grid grid-cols-[300px_auto] h-screen">
        <Aside />
        <div className="p-10 h-screen overflow-y-auto overflow-hidden">
          {children}
        </div>
      </div>
    </AdminGuardLayout>
  );
}
