import { Reporter } from "@/types/reporter";

export const awardedReporters: Reporter[] = [
    {
      id: 1,
      name: "Jane Doe",
      profileImage: "/images/reporter-1.jpg",
      reportTitle: "Improving Education in Northern Nigeria",
      likes: 1200,
      comments: 340,
      dateAwarded: "2024-11-15",
    },
    {
      id: 2,
      name: "John Smith",
      profileImage: "/images/reporter-2.jpg",
      reportTitle: "The Impact of Infrastructure Projects in Lagos",
      likes: 950,
      comments: 270,
      dateAwarded: "2024-11-10",
    },
    {
      id: 3,
      name: "Mary Johnson",
      profileImage: "/images/reporter-3.jpg",
      reportTitle: "Health Reforms in Rural Areas",
      likes: 1020,
      comments: 150,
      dateAwarded: "2024-11-12",
    },
    {
      id: 4,
      name: "Paul Brown",
      profileImage: "/images/reporter-4.jpg",
      reportTitle: "Youth Empowerment in Abuja",
      likes: 890,
      comments: 200,
      dateAwarded: "2024-11-13",
    },
    {
      id: 5,
      name: "Patricia Davis",
      profileImage: "/images/reporter-5.jpg",
      reportTitle: "Environmental Conservation in Rivers State",
      likes: 760,
      comments: 190,
      dateAwarded: "2024-11-11",
    },
    {
      id: 6,
      name: "James Wilson",
      profileImage: "/images/reporter-6.jpg",
      reportTitle: "Tackling Unemployment in Kano",
      likes: 1150,
      comments: 220,
      dateAwarded: "2024-11-14",
    },
    {
      id: 7,
      name: "Emily Moore",
      profileImage: "/images/reporter-7.jpg",
      reportTitle: "The Role of Women in Governance",
      likes: 980,
      comments: 260,
      dateAwarded: "2024-11-09",
    },
    {
      id: 8,
      name: "Michael Taylor",
      profileImage: "/images/reporter-8.jpg",
      reportTitle: "Analyzing Budget Allocation Trends",
      likes: 870,
      comments: 210,
      dateAwarded: "2024-11-08",
    },
    {
      id: 9,
      name: "Sophia Martinez",
      profileImage: "/images/reporter-9.jpg",
      reportTitle: "Building Stronger Institutions",
      likes: 890,
      comments: 300,
      dateAwarded: "2024-11-07",
    },
    {
      id: 10,
      name: "Christopher Anderson",
      profileImage: "/images/reporter-10.jpg",
      reportTitle: "Corruption and Accountability Measures",
      likes: 920,
      comments: 310,
      dateAwarded: "2024-11-06",
    },
    {
      id: 11,
      name: "Olivia Thomas",
      profileImage: "/images/reporter-11.jpg",
      reportTitle: "Promoting Access to Clean Water",
      likes: 850,
      comments: 240,
      dateAwarded: "2024-11-05",
    },
    {
      id: 12,
      name: "Matthew White",
      profileImage: "/images/reporter-12.jpg",
      reportTitle: "Technological Advancements in Agriculture",
      likes: 1180,
      comments: 270,
      dateAwarded: "2024-11-04",
    },
    {
      id: 13,
      name: "Isabella Jackson",
      profileImage: "/images/reporter-13.jpg",
      reportTitle: "The Importance of Education for All",
      likes: 1340,
      comments: 350,
      dateAwarded: "2024-11-03",
    },
    {
      id: 14,
      name: "Daniel Harris",
      profileImage: "/images/reporter-14.jpg",
      reportTitle: "The Power of Public-Private Partnerships",
      likes: 980,
      comments: 280,
      dateAwarded: "2024-11-02",
    },
    {
      id: 15,
      name: "Mia Martin",
      profileImage: "/images/reporter-15.jpg",
      reportTitle: "Analyzing National Security Strategies",
      likes: 910,
      comments: 230,
      dateAwarded: "2024-11-01",
    },
    {
      id: 16,
      name: "Ethan Thompson",
      profileImage: "/images/reporter-16.jpg",
      reportTitle: "Eradicating Illiteracy in Nigeria",
      likes: 1080,
      comments: 310,
      dateAwarded: "2024-10-31",
    },
    {
      id: 17,
      name: "Ava Garcia",
      profileImage: "/images/reporter-17.jpg",
      reportTitle: "Affordable Housing for All",
      likes: 940,
      comments: 290,
      dateAwarded: "2024-10-30",
    },
    {
      id: 18,
      name: "William Martinez",
      profileImage: "/images/reporter-18.jpg",
      reportTitle: "Infrastructure Development: A Case Study",
      likes: 870,
      comments: 200,
      dateAwarded: "2024-10-29",
    },
    {
      id: 19,
      name: "Emma Clark",
      profileImage: "/images/reporter-19.jpg",
      reportTitle: "Exploring Renewable Energy in Nigeria",
      likes: 910,
      comments: 260,
      dateAwarded: "2024-10-28",
    },
    {
      id: 20,
      name: "Liam Lewis",
      profileImage: "/images/reporter-20.jpg",
      reportTitle: "Digital Inclusion and its Benefits",
      likes: 1050,
      comments: 300,
      dateAwarded: "2024-10-27",
    },
    {
      id: 21,
      name: "Sophia Robinson",
      profileImage: "/images/reporter-21.jpg",
      reportTitle: "Improving Healthcare Accessibility",
      likes: 1190,
      comments: 340,
      dateAwarded: "2024-10-26",
    },
    {
      id: 22,
      name: "Benjamin Hall",
      profileImage: "/images/reporter-22.jpg",
      reportTitle: "Empowering SMEs in Nigeria",
      likes: 940,
      comments: 250,
      dateAwarded: "2024-10-25",
    },
    {
      id: 23,
      name: "Ella King",
      profileImage: "/images/reporter-23.jpg",
      reportTitle: "The Future of Nigerian Technology",
      likes: 970,
      comments: 220,
      dateAwarded: "2024-10-24",
    },
    {
      id: 24,
      name: "Oliver Wright",
      profileImage: "/images/reporter-24.jpg",
      reportTitle: "The Evolution of Transport Systems",
      likes: 860,
      comments: 190,
      dateAwarded: "2024-10-23",
    },
    {
      id: 25,
      name: "Amelia Hill",
      profileImage: "/images/reporter-25.jpg",
      reportTitle: "Reviving Nigerian Textile Industries",
      likes: 980,
      comments: 230,
      dateAwarded: "2024-10-22",
    },
    {
      id: 26,
      name: "Elijah Scott",
      profileImage: "/images/reporter-26.jpg",
      reportTitle: "The Rise of Local Content Development",
      likes: 1020,
      comments: 280,
      dateAwarded: "2024-10-21",
    },
    {
      id: 27,
      name: "Charlotte Green",
      profileImage: "/images/reporter-27.jpg",
      reportTitle: "Cultural Preservation in Nigeria",
      likes: 940,
      comments: 240,
      dateAwarded: "2024-10-20",
    },
    {
      id: 28,
      name: "Noah Adams",
      profileImage: "/images/reporter-28.jpg",
      reportTitle: "The Role of ICT in Rural Development",
      likes: 920,
      comments: 250,
      dateAwarded: "2024-10-19",
    },
    {
      id: 29,
      name: "Abigail Nelson",
      profileImage: "/images/reporter-29.jpg",
      reportTitle: "Effective Waste Management Strategies",
      likes: 850,
      comments: 210,
      dateAwarded: "2024-10-18",
    },
    {
      id: 30,
      name: "Alexander Carter",
      profileImage: "/images/reporter-30.jpg",
      reportTitle: "Fostering Creative Industries in Nigeria",
      likes: 1010,
      comments: 300,
      dateAwarded: "2024-10-17",
    },
  ];